export const songs = [
  {
    id: 1,
    titulo: 'Blinding Lights',
    artista: 'The Weeknd',
    album: 'After Hours',
    duracao: '3:20',
    genero: 'Pop',
    ano_lancamento: 2020,
  },
  {
    id: 2,
    titulo: 'Stairway to Heaven',
    artista: 'Led Zeppelin',
    album: 'Led Zeppelin IV',
    duracao: '8:02',
    genero: 'Rock Clássico',
    ano_lancamento: 1971,
  },
  {
    id: 3,
    titulo: 'Smooth',
    artista: 'Santana feat. Rob Thomas',
    album: 'Supernatural',
    duracao: '4:56',
    genero: 'Rock Latino',
    ano_lancamento: 1999,
  },
  {
    id: 4,
    titulo: 'Bad Guy',
    artista: 'Billie Eilish',
    album: 'When We All Fall Asleep, Where Do We Go?',
    duracao: '3:14',
    genero: 'Pop',
    ano_lancamento: 2019,
  },
  {
    id: 5,
    titulo: 'Bohemian Rhapsody',
    artista: 'Queen',
    album: 'A Night at the Opera',
    duracao: '5:55',
    genero: 'Rock Clássico',
    ano_lancamento: 1975,
  },
  {
    id: 6,
    titulo: 'Watermelon Sugar',
    artista: 'Harry Styles',
    album: 'Fine Line',
    duracao: '2:54',
    genero: 'Pop',
    ano_lancamento: 2019,
  },
  {
    id: 7,
    titulo: 'Smells Like Teen Spirit',
    artista: 'Nirvana',
    album: 'Nevermind',
    duracao: '5:01',
    genero: 'Grunge',
    ano_lancamento: 1991,
  },
  {
    id: 8,
    titulo: 'Hotline Bling',
    artista: 'Drake',
    album: 'Views',
    duracao: '4:27',
    genero: 'Rap',
    ano_lancamento: 2015,
  },
  {
    id: 9,
    titulo: 'Hotel California',
    artista: 'Eagles',
    album: 'Hotel California',
    duracao: '6:30',
    genero: 'Rock Clássico',
    ano_lancamento: 1977,
  },
  {
    id: 10,
    titulo: 'Shape of You',
    artista: 'Ed Sheeran',
    album: '÷',
    duracao: '3:54',
    genero: 'Pop',
    ano_lancamento: 2017,
  },
];

export default songs;
